Fix clippy warning
error: this comparison involving the minimum or maximum element for this type contains a case that is always true or always false
  --> /home/ding/rust-sgx-sdk/sgx_ucrypto/src/util.rs:22:8
   |
22 |     if destsz > SIZE_MAX || count > SIZE_MAX {
   |        ^^^^^^^^^^^^^^^^^
   |
   = note: #[deny(clippy::absurd_extreme_comparisons)] on by default
   = help: because SIZE_MAX is the maximum value for this type, this comparison is always false
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#absurd_extreme_comparisons